### ISSUE TITLE
You don't seem to have a generator with the name “bash” installed.

### ISSUE THREAD

**Issue by gionnivaleriana** [neatshell/generator-bash#1]
Ciao Claudio,

Yeoman keeps telling me that the bash generator is not installed.
I'm sure, of course, it's installed and the other generators I have on my machine (such as karma or angular) works like a charm.

I had already tried almost any solution google could provide me.
`yo doctor` says everything is ok, the `/node_modules/` global folder is in the correct position and it's correctly available in the `$PATH` variable, and I tried installing the generator both locally and globally (even tried to symlink the global installation to te project folder with `npm link [...]`) but the issue was not resolved with the same error message.
And obviously I already tried to uninstall/purge and than reinstall everything from yeoman, npm and node.js.

I think I can now exclude any issue caused by something wrong in my machine so I started to think that something is wrong in you package.
Something related to the dependency versions maybe?

My current setup:
* OS: Mac OS X 10.12.6 (build: 16G1036)
* Homebrew: 1.4.0
* Node: v9.3.0
* NPM: 5.6.0
* Yeoman: 2.0.0
* generator-bash: 1.4.1 (from `package.json`)

It seems that there's no other valid bash scaffolder/builder out there, so I really need you tool working.

Thanks!

**Comment by awelles** [comment]
dependencies were out of date in package.json. Up'd them to:

  "dependencies": {
    "chalk": "^2.4",
    "yeoman-generator": "^4.0",
    "yosay": "^2.0.0"
  },

This fixed the "you don't seem to have a generator with the name “bash”.

Pull request in.

**Comment by neatshell** [comment]
@gionnivaleriana  Sorry for the very loooong delay in the response. At the time you wrote the issue, the project was likely to be abandoned and I admit to haven't investigate, the same applies for the PR created by @awelles. But today I'm glad to have released a new major (working :) ) version and I am also working on the future release that introduce lot of new features, like handling of mandatory arguments, building of script with sub-commands and others...I'm also happy to announce that the project is not dead. Stay tuned ;)
